"""Input probing and compatibility gates."""

from __future__ import annotations

import hashlib
import json
import re
from dataclasses import dataclass
from pathlib import Path
from xml.etree.ElementTree import ParseError, iterparse

from rf_log_mcp.constants import (
    JSON_INPUT_PROFILE,
    MINIMUM_JSON_VERSION,
    SUPPORTED_XML_SCHEMA_VERSIONS,
    XML_INPUT_PROFILE,
)
from rf_log_mcp.errors import (
    InvalidFileTypeError,
    InvalidJsonError,
    InvalidXmlError,
    UnsupportedInputVersionError,
)

_XML_GENERATOR_PATTERN = re.compile(r"^(Robot|Rebot) (?P<major>\d+)\.(?P<minor>\d+)\b")
_JSON_GENERATOR_PATTERN = re.compile(r"^(Robot|Rebot) (?P<major>\d+)\.(?P<minor>\d+)\b")


@dataclass(slots=True)
class ProbedInput:
    path: Path
    source_format: str
    generator: str
    generated: str | None
    rpa: bool | None
    schemaversion: int | None
    input_profile: str


def sha256_file(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as stream:
        for chunk in iter(lambda: stream.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def probe_input(path: str | Path) -> ProbedInput:
    source = Path(path).expanduser().resolve()
    suffix = source.suffix.lower()
    if suffix == ".xml":
        return probe_xml_input(source)
    if suffix == ".json":
        return probe_json_input(source)
    raise InvalidFileTypeError("Only .xml and .json files are supported.")


def probe_xml_input(path: str | Path) -> ProbedInput:
    source = Path(path).expanduser().resolve()
    if source.suffix.lower() != ".xml":
        raise InvalidFileTypeError()
    if not source.exists():
        raise InvalidXmlError(f"Input file '{source}' does not exist.")

    try:
        parser = iterparse(source, events=("start",))
        _, root = next(parser)
        for _ in parser:
            pass
    except (ParseError, StopIteration) as exc:
        raise InvalidXmlError() from exc

    if root.tag != "robot":
        raise InvalidXmlError("Root element must be 'robot'.")

    generator = root.attrib.get("generator", "")
    generated = root.attrib.get("generated")
    rpa_raw = root.attrib.get("rpa")
    schemaversion_raw = root.attrib.get("schemaversion")

    if not schemaversion_raw:
        raise UnsupportedInputVersionError(
            "Input XML must declare a supported schemaversion from Robot/Rebot."
        )
    try:
        schemaversion = int(schemaversion_raw)
    except ValueError as exc:
        raise UnsupportedInputVersionError("schemaversion must be an integer.") from exc
    if schemaversion not in SUPPORTED_XML_SCHEMA_VERSIONS:
        raise UnsupportedInputVersionError(
            "Only Robot/Rebot XML with schemaversion 3, 4, or 5 is supported."
        )
    if not _is_supported_xml_generator(generator, schemaversion):
        raise UnsupportedInputVersionError(
            "Only Robot/Rebot 6.0.x XML (schemaversion=3), "
            "6.1+ XML (schemaversion=4), or 7.x XML (schemaversion=5) is supported. "
            f"Got '{generator or 'unknown'}' with schemaversion={schemaversion}."
        )

    rpa = None
    if rpa_raw is not None:
        rpa = rpa_raw.lower() == "true"

    return ProbedInput(
        path=source,
        source_format="xml",
        generator=generator,
        generated=generated,
        rpa=rpa,
        schemaversion=schemaversion,
        input_profile=XML_INPUT_PROFILE,
    )


def probe_json_input(path: str | Path) -> ProbedInput:
    source = Path(path).expanduser().resolve()
    if source.suffix.lower() != ".json":
        raise InvalidFileTypeError("Only .json files are supported.")
    if not source.exists():
        raise InvalidJsonError(f"Input file '{source}' does not exist.")

    try:
        with source.open("r", encoding="utf-8") as stream:
            data = json.load(stream)
    except json.JSONDecodeError as exc:
        raise InvalidJsonError() from exc

    if not isinstance(data, dict):
        raise InvalidJsonError("Top-level JSON value must be an object.")
    if not isinstance(data.get("suite"), dict):
        raise InvalidJsonError("Top-level JSON object must contain a 'suite' object.")

    generator = data.get("generator")
    if not isinstance(generator, str):
        raise UnsupportedInputVersionError(
            "Input JSON must declare a Robot/Rebot generator from version 7.2 or newer."
        )
    if not _is_supported_json_generator(generator):
        minimum = ".".join(str(part) for part in MINIMUM_JSON_VERSION)
        raise UnsupportedInputVersionError(
            f"Only JSON generated by Robot/Rebot {minimum}+ is supported. "
            f"Got '{generator or 'unknown'}'."
        )

    generated = data.get("generated")
    if generated is not None and not isinstance(generated, str):
        raise InvalidJsonError("'generated' must be a string when present.")
    rpa = data.get("rpa")
    if rpa is not None and not isinstance(rpa, bool):
        raise InvalidJsonError("'rpa' must be a boolean when present.")

    return ProbedInput(
        path=source,
        source_format="json",
        generator=generator,
        generated=generated,
        rpa=rpa,
        schemaversion=None,
        input_profile=JSON_INPUT_PROFILE,
    )


def _is_supported_json_generator(generator: str) -> bool:
    match = _JSON_GENERATOR_PATTERN.match(generator)
    if not match:
        return False
    major = int(match.group("major"))
    minor = int(match.group("minor"))
    return (major, minor) >= MINIMUM_JSON_VERSION


def _is_supported_xml_generator(generator: str, schemaversion: int) -> bool:
    match = _XML_GENERATOR_PATTERN.match(generator)
    if not match:
        return False
    major = int(match.group("major"))
    minor = int(match.group("minor"))
    if schemaversion == 3:
        return major == 6 and minor == 0
    if schemaversion == 4:
        return major == 6 and minor >= 1
    if schemaversion == 5:
        return major == 7
    return False
